const STORAGE_KEYS = {
   BUILD_ROUTER_VERSION: 'BUILD_ROUTER_VERSION',
   DOCKER_DID_SETUP: 'DOCKER_DID_SETUP',
}

const ROUTER_VERSION = '0.0.21';

export {
   ROUTER_VERSION,
}

export default STORAGE_KEYS;
