enum STORAGE_KEYS {
  NAKA_WALLET_API_ACCESS_TOKEN = 'NAKA_WALLET_API_ACCESS_TOKEN',
  NAKA_WALLET_AUTHEN = 'NAKA_WALLET_AUTHEN',
  ANONYMOUS_AUTH_TOKEN = 'ANONYMOUS_AUTH_TOKEN',
}

export default STORAGE_KEYS;