enum STORAGE_KEYS {
  AGENTS_HAS_WALLET = 'AGENTS_HAS_WALLET',
  AGENTS_HAS_BACKUP_PRV_KEY = 'AGENTS_HAS_BACKUP_PRV_KEY',
  AUTHEN_TOKEN = 'AUTHEN_TOKEN',
  WALLET_ADDRESS = 'WALLET_ADDRESS',
  RECENT_AGENTS = 'RECENT_AGENTS',
  INSTALLED_SOCIAL_AGENTS = 'INSTALLED_SOCIAL_AGENTS',
}

export default STORAGE_KEYS;